#!/usr/bin/env bash
# =============================================================================
# run0a-checker-mixed-samples-grid.sh
# -----------------------------------------------------------------------------
# Verify the block-size grid generated by run0b-build-mixed-samples-grid.sh
# against the original HWC + AGC source CSV.
#
# Wraps src/app/checker_mixed_samples_grid.java. The Java program checks each
# mixed_sample_*.py / mixed_sample_*.labels.tsv pair under each blocks_NN
# subdir, plus the per-block source-CSV agreement.
#
# Outputs (per-setting + overall):
#   files checked : N
#   blocks checked: M
#   errors        : K
#
# Usage
#   bash src/app/run0a-checker-mixed-samples-grid.sh
#
# Customization (env vars)
#   GRID_ROOT          - grid root dir (default: src/app/data_mixed_samples_grid_480)
#   SOURCE_CSV         - HWC+AGC source CSV (default derived from MODEL_NAME/DATASET_SIZE)
#   MODEL_NAME         - used to derive SOURCE_CSV (default: starcoder2-15b-instruct-v0.1)
#   DATASET_SIZE       - used to derive SOURCE_CSV (default: 2700)
#   PATTERN            - subdir glob under GRID_ROOT (default: blocks_*)
#   MAX_ERRORS         - cap on printed errors (default: 50)
#   STRICT=1           - abort on first error
#   VERBOSE=1          - per-file progress output
#   JAVAC, JAVA        - override compiler/runtime binaries
#   JAVA_CLASS_DIR     - where to put the .class (default: alongside the .java)
# =============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# Resolve repo root from this script's location.
#   This script lives in src/app/, so repo root is two dirs above.
# -----------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

cd "${REPO_ROOT}"

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------
TS="$(date +'%Y%m%d_%H%M%S')"
LOG_DIR="${LOG_DIR:-${REPO_ROOT}/src/logs}"
LOG_FILE="${LOG_FILE:-${LOG_DIR}/run0a-checker-mixed-samples-grid_${TS}.log}"
mkdir -p "${LOG_DIR}"
exec > >(tee -a "${LOG_FILE}") 2>&1

echo "Log file : ${LOG_FILE}"
echo "Started  : $(date -Is)"
echo "Repo root: ${REPO_ROOT}"
echo

# -----------------------------------------------------------------------------
# Editable configuration
# -----------------------------------------------------------------------------
MODEL_NAME="${MODEL_NAME:-starcoder2-15b-instruct-v0.1}"
DATASET_SIZE="${DATASET_SIZE:-2700}"

GRID_ROOT="${GRID_ROOT:-src/app/data_mixed_samples_grid_480}"
SOURCE_CSV="${SOURCE_CSV:-src/code-analyzer-tree-sitter/data_codesearchnet/${MODEL_NAME}/ast/codesearchnet_${MODEL_NAME}_python_merged_${DATASET_SIZE}.csv}"

PATTERN="${PATTERN:-blocks_*}"
MAX_ERRORS="${MAX_ERRORS:-50}"

JAVAC="${JAVAC:-javac}"
JAVA="${JAVA:-java}"
# Compiled .class files live under SCRIPT_DIR/.build_java/<program>/ to keep
# src/app/ free of build artifacts. To run by hand:
#   java -cp src/app/.build_java/checker_mixed_samples_grid checker_mixed_samples_grid --help
BUILD_JAVA=".build_java/checker_mixed_samples_grid"

JAVA_SRC="${SCRIPT_DIR}/checker_mixed_samples_grid.java"
JAVA_CLASS_DIR="${JAVA_CLASS_DIR:-${SCRIPT_DIR}/${BUILD_JAVA}}"
JAVA_CLASS_NAME="checker_mixed_samples_grid"

# -----------------------------------------------------------------------------
# Sanity checks
# -----------------------------------------------------------------------------
if [ ! -f "${JAVA_SRC}" ]; then
  echo "[ERROR] Java source not found: ${JAVA_SRC}" >&2
  exit 2
fi
if [ ! -d "${GRID_ROOT}" ]; then
  echo "[ERROR] grid root not found: ${GRID_ROOT}" >&2
  exit 2
fi
if [ ! -f "${SOURCE_CSV}" ]; then
  echo "[ERROR] source CSV not found: ${SOURCE_CSV}" >&2
  exit 2
fi
if ! command -v "${JAVAC}" >/dev/null 2>&1; then
  echo "[ERROR] javac not found: ${JAVAC}" >&2
  exit 2
fi

# -----------------------------------------------------------------------------
# Optional flags
# -----------------------------------------------------------------------------
EXTRA_ARGS=()
if [ "${VERBOSE:-0}" = "1" ]; then
  EXTRA_ARGS+=(--verbose)
fi
if [ "${STRICT:-0}" = "1" ]; then
  EXTRA_ARGS+=(--strict)
fi

# -----------------------------------------------------------------------------
# Compile
# -----------------------------------------------------------------------------
echo "Compiling : ${JAVA_SRC}"
echo "Class dir : ${JAVA_CLASS_DIR}"
"${JAVAC}" -d "${JAVA_CLASS_DIR}" "${JAVA_SRC}"
echo

# -----------------------------------------------------------------------------
# Run
# -----------------------------------------------------------------------------
echo "============================================================"
echo " run0a-checker-mixed-samples-grid.sh"
echo "   model name  : ${MODEL_NAME}"
echo "   dataset size: ${DATASET_SIZE}"
echo "   grid root   : ${GRID_ROOT}"
echo "   source csv  : ${SOURCE_CSV}"
echo "   pattern     : ${PATTERN}"
echo "   max errors  : ${MAX_ERRORS}"
echo "   verbose     : ${VERBOSE:-0}"
echo "   strict      : ${STRICT:-0}"
echo "   class dir   : ${JAVA_CLASS_DIR}"
echo "============================================================"
echo

set +e
"${JAVA}" -cp "${JAVA_CLASS_DIR}" "${JAVA_CLASS_NAME}" \
  --grid-root  "${GRID_ROOT}" \
  --source-csv "${SOURCE_CSV}" \
  --pattern    "${PATTERN}" \
  --max-errors "${MAX_ERRORS}" \
  "${EXTRA_ARGS[@]}" \
  "$@"
JAVA_RC=$?
set -e

echo
echo "Finished : $(date -Is)"
echo "Exit code: ${JAVA_RC}"
echo "Log file : ${LOG_FILE}"

exit "${JAVA_RC}"